// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	UserID              int32
	UserUuid            []byte
	Username            string
	Email               sql.NullString
	Phone               sql.NullString
	PasswordHash        string
	UserPrivilege       int8
	UserBalance         string
	UserStatus          int8
	AvatarPath          string
	MfaEnabled          int8
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           sql.NullTime
	LastLoginAt         sql.NullTime
	LastLoginIp         sql.NullString
	PasswordUpdatedAt   time.Time
	FailedLoginAttempts int32
	LockedUntil         sql.NullTime
}
