// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetActiveUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetActiveUserByLoginIdentifier(ctx context.Context, arg GetActiveUserByLoginIdentifierParams) (User, error)
	GetActiveUserByPhone(ctx context.Context, phone sql.NullString) (User, error)
	GetActiveUserByUUID(ctx context.Context, userUuid []byte) (User, error)
	GetActiveUserByUsername(ctx context.Context, username string) (User, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetUserByID(ctx context.Context, userID int32) (User, error)
	GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error)
	GetUserByUUID(ctx context.Context, userUuid []byte) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementFailedLoginAttempts(ctx context.Context, userID int32) error
	SetLockedUntil(ctx context.Context, arg SetLockedUntilParams) error
	SoftDeleteUser(ctx context.Context, userID int32) error
	UpdateAvatarPath(ctx context.Context, arg UpdateAvatarPathParams) error
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) error
	UpdateLoginSuccess(ctx context.Context, arg UpdateLoginSuccessParams) error
	UpdateMFAEnabled(ctx context.Context, arg UpdateMFAEnabledParams) error
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdatePhone(ctx context.Context, arg UpdatePhoneParams) error
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error
	UpdateUserPrivilege(ctx context.Context, arg UpdateUserPrivilegeParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error
}

var _ Querier = (*Queries)(nil)
