// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	UserUuid      []byte
	Username      string
	Email         sql.NullString
	Phone         sql.NullString
	PasswordHash  string
	UserPrivilege int8
	UserBalance   string
	UserStatus    int8
	AvatarPath    string
	MfaEnabled    int8
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.UserUuid,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.UserPrivilege,
		arg.UserBalance,
		arg.UserStatus,
		arg.AvatarPath,
		arg.MfaEnabled,
	)
}

const getActiveUserByEmail = `-- name: GetActiveUserByEmail :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE email = ?
    AND user_status = 1
`

func (q *Queries) GetActiveUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getActiveUserByLoginIdentifier = `-- name: GetActiveUserByLoginIdentifier :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE user_status = 1
    AND (username = ? OR email = ? OR phone = ?)
`

type GetActiveUserByLoginIdentifierParams struct {
	Username string
	Email    sql.NullString
	Phone    sql.NullString
}

func (q *Queries) GetActiveUserByLoginIdentifier(ctx context.Context, arg GetActiveUserByLoginIdentifierParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByLoginIdentifier, arg.Username, arg.Email, arg.Phone)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getActiveUserByPhone = `-- name: GetActiveUserByPhone :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE phone = ?
    AND user_status = 1
`

func (q *Queries) GetActiveUserByPhone(ctx context.Context, phone sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getActiveUserByUUID = `-- name: GetActiveUserByUUID :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE user_uuid = ?
    AND user_status = 1
`

func (q *Queries) GetActiveUserByUUID(ctx context.Context, userUuid []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByUUID, userUuid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getActiveUserByUsername = `-- name: GetActiveUserByUsername :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE username = ?
    AND user_status = 1
`

func (q *Queries) GetActiveUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE user_id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE phone = ?
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE user_uuid = ?
`

func (q *Queries) GetUserByUUID(ctx context.Context, userUuid []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, userUuid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    user_id,
    user_uuid,
    username,
    email,
    phone,
    password_hash,
    user_privilege,
    user_balance,
    user_status,
    avatar_path,
    mfa_enabled,
    created_at,
    updated_at,
    deleted_at,
    last_login_at,
    last_login_ip,
    password_updated_at,
    failed_login_attempts,
    locked_until
FROM users
WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserPrivilege,
		&i.UserBalance,
		&i.UserStatus,
		&i.AvatarPath,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :exec
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1
WHERE user_id = ?
`

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, incrementFailedLoginAttempts, userID)
	return err
}

const setLockedUntil = `-- name: SetLockedUntil :exec
UPDATE users
SET locked_until = ?
WHERE user_id = ?
`

type SetLockedUntilParams struct {
	LockedUntil sql.NullTime
	UserID      int32
}

func (q *Queries) SetLockedUntil(ctx context.Context, arg SetLockedUntilParams) error {
	_, err := q.db.ExecContext(ctx, setLockedUntil, arg.LockedUntil, arg.UserID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET user_status = 0, deleted_at = NOW()
WHERE user_id = ?
`

func (q *Queries) SoftDeleteUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, userID)
	return err
}

const updateAvatarPath = `-- name: UpdateAvatarPath :exec
UPDATE users
SET avatar_path = ?
WHERE user_id = ?
`

type UpdateAvatarPathParams struct {
	AvatarPath string
	UserID     int32
}

func (q *Queries) UpdateAvatarPath(ctx context.Context, arg UpdateAvatarPathParams) error {
	_, err := q.db.ExecContext(ctx, updateAvatarPath, arg.AvatarPath, arg.UserID)
	return err
}

const updateEmail = `-- name: UpdateEmail :exec
UPDATE users
SET email = ?
WHERE user_id = ?
`

type UpdateEmailParams struct {
	Email  sql.NullString
	UserID int32
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateEmail, arg.Email, arg.UserID)
	return err
}

const updateLoginSuccess = `-- name: UpdateLoginSuccess :exec
UPDATE users
SET last_login_at = NOW(),
        last_login_ip = ?,
        failed_login_attempts = 0,
        locked_until = NULL
WHERE user_id = ?
`

type UpdateLoginSuccessParams struct {
	LastLoginIp sql.NullString
	UserID      int32
}

func (q *Queries) UpdateLoginSuccess(ctx context.Context, arg UpdateLoginSuccessParams) error {
	_, err := q.db.ExecContext(ctx, updateLoginSuccess, arg.LastLoginIp, arg.UserID)
	return err
}

const updateMFAEnabled = `-- name: UpdateMFAEnabled :exec
UPDATE users
SET mfa_enabled = ?
WHERE user_id = ?
`

type UpdateMFAEnabledParams struct {
	MfaEnabled int8
	UserID     int32
}

func (q *Queries) UpdateMFAEnabled(ctx context.Context, arg UpdateMFAEnabledParams) error {
	_, err := q.db.ExecContext(ctx, updateMFAEnabled, arg.MfaEnabled, arg.UserID)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users
SET password_hash = ?, password_updated_at = NOW()
WHERE user_id = ?
`

type UpdatePasswordHashParams struct {
	PasswordHash string
	UserID       int32
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordHash, arg.PasswordHash, arg.UserID)
	return err
}

const updatePhone = `-- name: UpdatePhone :exec
UPDATE users
SET phone = ?
WHERE user_id = ?
`

type UpdatePhoneParams struct {
	Phone  sql.NullString
	UserID int32
}

func (q *Queries) UpdatePhone(ctx context.Context, arg UpdatePhoneParams) error {
	_, err := q.db.ExecContext(ctx, updatePhone, arg.Phone, arg.UserID)
	return err
}

const updateUserBalance = `-- name: UpdateUserBalance :exec
UPDATE users
SET user_balance = ?
WHERE user_id = ?
`

type UpdateUserBalanceParams struct {
	UserBalance string
	UserID      int32
}

func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBalance, arg.UserBalance, arg.UserID)
	return err
}

const updateUserPrivilege = `-- name: UpdateUserPrivilege :exec
UPDATE users
SET user_privilege = ?
WHERE user_id = ?
`

type UpdateUserPrivilegeParams struct {
	UserPrivilege int8
	UserID        int32
}

func (q *Queries) UpdateUserPrivilege(ctx context.Context, arg UpdateUserPrivilegeParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPrivilege, arg.UserPrivilege, arg.UserID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET user_status = ?
WHERE user_id = ?
`

type UpdateUserStatusParams struct {
	UserStatus int8
	UserID     int32
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.UserStatus, arg.UserID)
	return err
}

const updateUsername = `-- name: UpdateUsername :exec
UPDATE users
SET username = ?
WHERE user_id = ?
`

type UpdateUsernameParams struct {
	Username string
	UserID   int32
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateUsername, arg.Username, arg.UserID)
	return err
}
