// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AuthRefreshToken struct {
	RefreshTokenID []byte
	UserUuid       []byte
	TokenHash      []byte
	IssuedAt       time.Time
	ExpiresAt      time.Time
	RevokedAt      sql.NullTime
	LastUsedAt     sql.NullTime
	ReplacedByID   sql.NullString
	CreatedIp      sql.NullString
	UserAgent      sql.NullString
}
