// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	GetActiveRefreshTokenByHash(ctx context.Context, tokenHash []byte) (AuthRefreshToken, error)
	GetRefreshTokenByID(ctx context.Context, refreshTokenID []byte) (AuthRefreshToken, error)
	RevokeRefreshToken(ctx context.Context, refreshTokenID []byte) error
	RevokeRefreshTokensForUser(ctx context.Context, userUuid []byte) error
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error
	UpdateRefreshTokenLastUsed(ctx context.Context, refreshTokenID []byte) error
}

var _ Querier = (*Queries)(nil)
