// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO auth_refresh_tokens (
    refresh_token_id,
    user_uuid,
    token_hash,
    expires_at,
    created_ip,
    user_agent
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateRefreshTokenParams struct {
	RefreshTokenID []byte
	UserUuid       []byte
	TokenHash      []byte
	ExpiresAt      time.Time
	CreatedIp      sql.NullString
	UserAgent      sql.NullString
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.RefreshTokenID,
		arg.UserUuid,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedIp,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM auth_refresh_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens)
	return err
}

const getActiveRefreshTokenByHash = `-- name: GetActiveRefreshTokenByHash :one
SELECT
    refresh_token_id,
    user_uuid,
    token_hash,
    issued_at,
    expires_at,
    revoked_at,
    last_used_at,
    replaced_by_id,
    created_ip,
    user_agent
FROM auth_refresh_tokens
WHERE token_hash = ?
    AND revoked_at IS NULL
    AND expires_at > NOW()
`

func (q *Queries) GetActiveRefreshTokenByHash(ctx context.Context, tokenHash []byte) (AuthRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getActiveRefreshTokenByHash, tokenHash)
	var i AuthRefreshToken
	err := row.Scan(
		&i.RefreshTokenID,
		&i.UserUuid,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.ReplacedByID,
		&i.CreatedIp,
		&i.UserAgent,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT
    refresh_token_id,
    user_uuid,
    token_hash,
    issued_at,
    expires_at,
    revoked_at,
    last_used_at,
    replaced_by_id,
    created_ip,
    user_agent
FROM auth_refresh_tokens
WHERE refresh_token_id = ?
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, refreshTokenID []byte) (AuthRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByID, refreshTokenID)
	var i AuthRefreshToken
	err := row.Scan(
		&i.RefreshTokenID,
		&i.UserUuid,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.ReplacedByID,
		&i.CreatedIp,
		&i.UserAgent,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE auth_refresh_tokens
SET revoked_at = NOW()
WHERE refresh_token_id = ?
    AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, refreshTokenID []byte) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, refreshTokenID)
	return err
}

const revokeRefreshTokensForUser = `-- name: RevokeRefreshTokensForUser :exec
UPDATE auth_refresh_tokens
SET revoked_at = NOW()
WHERE user_uuid = ?
    AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensForUser(ctx context.Context, userUuid []byte) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokensForUser, userUuid)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE auth_refresh_tokens
SET revoked_at = NOW(),
    replaced_by_id = ?,
    last_used_at = NOW()
WHERE refresh_token_id = ?
    AND revoked_at IS NULL
`

type RotateRefreshTokenParams struct {
	ReplacedByID   sql.NullString
	RefreshTokenID []byte
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, rotateRefreshToken, arg.ReplacedByID, arg.RefreshTokenID)
	return err
}

const updateRefreshTokenLastUsed = `-- name: UpdateRefreshTokenLastUsed :exec
UPDATE auth_refresh_tokens
SET last_used_at = NOW()
WHERE refresh_token_id = ?
`

func (q *Queries) UpdateRefreshTokenLastUsed(ctx context.Context, refreshTokenID []byte) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenLastUsed, refreshTokenID)
	return err
}
