CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    user_uuid BINARY(16) NOT NULL,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(255) NULL,
    phone VARCHAR(32) NULL,
    password_hash VARCHAR(255) NOT NULL,
    user_privilege TINYINT NOT NULL DEFAULT 0,
    user_balance DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    user_status TINYINT NOT NULL DEFAULT 1,
    avatar_path VARCHAR(255) NULL,
    mfa_enabled TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    last_login_at DATETIME NULL,
    last_login_ip VARCHAR(45) NULL,
    password_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    failed_login_attempts INT NOT NULL DEFAULT 0,
    locked_until DATETIME NULL,
    UNIQUE KEY uk_users_uuid (user_uuid),
    UNIQUE KEY uk_users_username (username),
    UNIQUE KEY uk_users_email (email),
    UNIQUE KEY uk_users_phone (phone),
    KEY idx_users_status_privilege (user_status, user_privilege)
);
